### ISSUE TITLE
ABI_ENCODED_DATA

### ISSUE THREAD

**Issue by huahuayu** [fxfactorial/run-evm-code#1]
what is the `<ABI_ENCODED_DATA>` in readme, how to get/generate it?

if there's some test case that will be good.

**Comment by fxfactorial** [comment]
It’s any kind of byte code , usually assumed to be abi encoded . Basically any kind of smart contract call

**Comment by huahuayu** [comment]
what I know how to generate this abi_encoded_data is to use abigen go code with noSend option, get the transaction then parse the data field. But it is a little bit tricky. Do you have other methods?

**Comment by fxfactorial** [comment]
It could be that way or you could use web3 or ethers (both in JavaScript ) it doesn’t matter what tool you use , as long as it makes solidity based ABI codes

**Comment by huahuayu** [comment]
yes, I see that, so what method do you use?

**Comment by fxfactorial** [comment]
I factored this code out of another project I have but that is not open source - I use it it mainly to replay previous arbitrage things
