### ISSUE TITLE
what it is the typical use case

### ISSUE THREAD

**Issue by huahuayu** [fxfactorial/run-evm-code#2]
hi, so I know it can execute tx call in a certain block, but when do you do that? What's the scenario?

**Comment by fxfactorial** [comment]
Hmm - maybe I wanted to check balanceOf weth of someone at a previous block number - this tool lets you do that

**Comment by huahuayu** [comment]
so it also can be used to check uniswap pair reverses and it very efficient compare to rpc call?

**Comment by fxfactorial** [comment]
Yes that’s possible but probably not best since you probably always want an updating db (db here doesn’t update , just what whatever chain data is at moment )
