### ISSUE TITLE
Resource temporarily unavailable 

### ISSUE THREAD

**Issue by hwiceberg** [fxfactorial/run-evm-code#3]
```
$ ./run-evm-code -blknum 12454536  -db_dir ~/node/geth/chaindata -receiver 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 -sender 0xfdbe95ec43ca5c77929a1c30e9ee588c28c5c9b4 0xd0e30db0
INFO [05-17|15:14:28.961] Allocated cache and file handles         database=~/node/geth/chaindata cache=48.00MiB handles=48
2021/05/17 15:14:28 resource temporarily unavailable
```

I encountered this after running the script for [a transaction](https://etherscan.io/tx/0x56c5c23965347229b4a339872b660a3f621497ee55c4199a15d2a74e641a349a) on eth mainnet, am I using this tool correctly?

**Comment by hwiceberg** [comment]
Resolved by turning off the geth, could be that geth has a read lock on the db.

**Comment by fxfactorial** [comment]
Exactly - need to mention it in Readme -
