### ISSUE TITLE
resource temporarily unavailable

### ISSUE THREAD

**Issue by huahuayu** [fxfactorial/run-evm-code#4]
hi, I want to have a try, to execute a random tx call which I picked from etherscan, which is this https://etherscan.io/tx/0x6be55a2e876e06c3ff02ed8be96951ff297f79cdcc4d5a282cc14fbed55f371b

so the input should be like this

```
./run-evm-code \
        -blknum 12452785  \
        -db_dir /mnt/data/ethereum/mainnet/geth/chaindata \
        -receiver 0x514910771af9ca656af840dff83e8264ecf986ca \
        -sender 0x12f55c1ab94c56212929f19f48b4030aa83dd54c 0xa9059cbb000000000000000000000000e8fdf6ed054c9a46dd1299a64abef85210b0521d000000000000000000000000000000000000000000000018a6ab24f512f49b05
```

I have a keep synced geth client running, but the result is:

```
INFO [05-18|09:56:43.695] Allocated cache and file handles         database=/mnt/data/ethereum/mainnet/geth/chaindata cache=48.00MiB handles=48
2021/05/18 09:56:43 resource temporarily unavailable
```

what's the problem?

**Comment by fxfactorial** [comment]
You can't have the node running at the same time as you use this tool

**Comment by huahuayu** [comment]
what a big limitation

**Comment by fxfactorial** [comment]
PRs welcome

**Comment by fxfactorial** [comment]
Actually this is not really fixable since the issue is coming up from low level leveldb itself
